# Generated by Django 4.1.5 on 2023-02-19 04:23

from django.db import migrations, models
import django.db.models.deletion
import energyplants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(max_length=100, unique=True)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidades', models.CharField(choices=[('$/MWh', 'Dolares por Megawatts-hora'), ('$/MMBTU', 'Dolares por Millon de BTU')], default='$/MWh', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('coordenadas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='energyplants.coordenadas')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('tipogen', models.CharField(max_length=100)),
                ('renovable', models.BooleanField(default=False)),
                ('eficiencia', models.PositiveSmallIntegerField(validators=[energyplants.models.validate_min_max_value])),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='energyplants.combustible')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unidades', models.CharField(choices=[('KW', 'Kilowatts'), ('MW', 'Megawatts'), ('MMBTU/hr', 'Millon de BTU/Hora')], default='MW', max_length=8)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='energyplants.lugar')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='energyplants.tipo')),
            ],
        ),
    ]
