# Generated by Django 4.1.5 on 2023-02-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyplants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='TipoPlanta',
        ),
    ]
