# Generated by Django 4.1.5 on 2023-02-19 05:11

from django.db import migrations, models
import energyplants.models


class Migration(migrations.Migration):

    dependencies = [
        ('energyplants', '0003_planta_actualizado_planta_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='costo',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[energyplants.models.validate_positive_value]),
        ),
        migrations.AlterField(
            model_name='planta',
            name='capacidad',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[energyplants.models.validate_positive_value]),
        ),
    ]
