# Generated by Django 4.1.5 on 2023-02-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyplants', '0004_alter_combustible_costo_alter_planta_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='coordenadas',
        ),
        migrations.DeleteModel(
            name='Coordenadas',
        ),
    ]
