# Generated by Django 4.1.5 on 2023-02-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energyplants', '0005_remove_lugar_coordenadas_delete_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplanta',
            name='combustible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='energyplants.combustible'),
        ),
    ]
